version: "3.9"

services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config.alloy:/etc/alloy/config.alloy:ro
    command: ["run", "/etc/alloy/config.alloy"]
    restart: unless-stopped
    labels:
      service_name: alloy
